name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm test

  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        milliseconds: 1000

  clean:
    runs-on: ubuntu-latest
    steps:
      - name: cleanup
        uses: ngduc/clean-up-action@master
        with:
          userId: setYourUserId # set your userId, example: userNameProjectName
          expiryMins: 1 # after X minutes, invoke the below URL endpoint.
          postUrl: https://end53hx4vqglh.x.pipedream.net/ # some URL endpoint to clean up resources.
          postPayload: '{ "someResourceId": 1234 }'